controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        de: '' # don't prefix URLs for English, the default locale
        en: '/en'
    requirements:
        _locale: '%locales%'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
